apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shoply
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/incheon-soda/shoply-frontend:870e06700c866c43781711e2eeb71556fd292a2f
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "50m"
            memory: "64Mi"
        envFrom:
        - configMapRef:
            name: db-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shoply
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80